[package]
name = "phonolyze"
version = "0.1.0"
edition = "2021"
description = "Visualize sound files"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.71"
bytemuck = { version = "1.13.1", features = ["derive"] }
cfg-if = "1.0.0"
clap = { version = "4.3.0", features = ["derive"] }
colorgrad = "0.6.2"
cpal = { version = "0.15.2", features = ["wasm-bindgen"] }
env_logger = "0.10.0"
hound = "3.5.0"
image = "0.24.6"
instant = "0.1.12"
log = "0.4.17"
noize = { path = "../noize" }
ordered-float = "3.7.0"
plotters = "0.3.4"
pollster = "0.3.0"
rustfft = "6.1.0"
symphonia = { version = "0.5.2", features = ["all"] }
tailog = { path = "../tailog" }
wgpu = "0.16.0"
winit = "0.28.3"
#egui = "0.21.0"
#egui-wgpu = "0.21.0"
#egui-winit = "0.21.1"
#egui = { path = "/home/zach/cratesio/egui/crates/egui" }
#egui-wgpu = { path = "/home/zach/cratesio/egui/crates/egui-wgpu" }
#egui-winit = { path = "/home/zach/cratesio/egui/crates/egui-winit" }
#easer = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
reqwest = "0.11.17"
wgpu = { version = "0.16", features = ["webgl"]}
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
web-sys = { version = "0.3.61", features = [
    "Document",
    "Element",
    "Location",
    "Window",
]}


[build-dependencies]
anyhow = "1.0.71"
fs_extra = "1.3.0"
